export const projects = [
  {
    title: 'WanderMath',
    description: "WanderMath is an Augmented Reality (AR) experience to help 4th and 5th graders engage in open-ended math adventures.",
    image: '/images/WanderMath.png',
    tags: ['Unity3D', 'ARCore', 'IOS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Pop-Task',
    description: "Pop-task is a work assignment and management resource that improves your efficiency and motivations to work no matter in school, in company or even at home.",
    image: '/images/PopTask.png',
    tags: ['React.js', 'TailwindCSS', 'Django', 'AWS'],
    source: 'https://google.com',
    visit: '/work/PopTask',
    id: 1,
  },
  {
    title: 'Paper Crane',
    description: "Paper Crane is an AR game with facial detection feature which is aiming to letting our players feel freedom as well as enjoy the gameplay experience we designed for them.",
    image: '/images/PaperCrane.png',
    tags: ['Unity3D', 'OpenCV',],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Todo-ist',
    description: "Todo-ist is a cloned project which implemented the main feature and UI of the real ‘Todoist’  by using ReactJS and FireBase.  ",
    image: '/images/Todoiest.png',
    tags: ['React.js', 'SCSS', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
];

export const webProjects = [
  {
    title: 'Pop-Task',
    description: "Pop-task is a work assignment and management resource that improves your efficiency and motivations to work no matter in school, in company or even at home.",
    image: '/images/PopTask.png',
    tags: ['React.js', 'TailwindCSS', 'Django', 'AWS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Todo-ist',
    description: "Pop-task is a work assignment and management resource that improves your efficiency and motivations to work no matter in school, in company or even at home.",
    image: '/images/Todoiest.png',
    tags: ['React.js', 'SCSS', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Tetris',
    description: "Pop-task is a work assignment and management resource that improves your efficiency and motivations to work no matter in school, in company or even at home.",
    image: '/images/Tetris.png',
    tags: ['React.js', 'CSS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
]

export const gameProjects = [
  {
    title: 'WanderMath',
    description: "WanderMath is an Augmented Reality (AR) experience to help 4th and 5th graders engage in open-ended math adventures.",
    image: '/images/WanderMath.png',
    tags: ['Unity3D', 'ARCore', 'IOS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Paper Crane',
    description: "Paper Crane is an AR game with facial detection feature which is aiming to letting our players feel freedom as well as enjoy the gameplay experience we designed for them.",
    image: '/images/PaperCrane.png',
    tags: ['Unity3D', 'OpenCV',],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Blindspot',
    description: "Paper Crane is an AR game with facial detection feature which is aiming to letting our players feel freedom as well as enjoy the gameplay experience we designed for them.",
    image: '/images/BlindSpot.png',
    tags: ['Unity3D', 'WebGl',],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Shopi-fight',
    description: "Paper Crane is an AR game with facial detection feature which is aiming to letting our players feel freedom as well as enjoy the gameplay experience we designed for them.",
    image: '/images/Shopifight.png',
    tags: ['Unity3D', 'Photon Engine',],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Hit.n.Run',
    description: "Paper Crane is an AR game with facial detection feature which is aiming to letting our players feel freedom as well as enjoy the gameplay experience we designed for them.",
    image: '/images/HitNRun.png',
    tags: ['Unity3D'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
]

export const TimeLineData = [
  { year: 2015, text: 'Studied at UC Irvine as an undergraduate student majored in CS', },
  { year: 2018, text: 'Participated my first Game Jam and finished a game in 48 hours', },
  { year: 2019, text: 'Joined Datamimo as a Software Engineer intern (Machine Learning)' },
  { year: 2020, text: 'Admitted into Carnegie Mellon University as a graduate student', },
  { year: 2022, text: 'Joined CarGurus as a Software Engineer co-op (Front-End)', },
];